// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    CssVar: typeof import('./src/components/CssVar.vue')['default']
    DigitDisplay: typeof import('./src/components/DigitDisplay.vue')['default']
    GameCell: typeof import('./src/components/GameCell.vue')['default']
    GameGrid: typeof import('./src/components/GameGrid.vue')['default']
    GamePanel: typeof import('./src/components/GamePanel.vue')['default']
    GamePanelBottom: typeof import('./src/components/GamePanelBottom.vue')['default']
    GamePanelTop: typeof import('./src/components/GamePanelTop.vue')['default']
  }
}

export { }
